FROM php7.1-nginx:stable

LABEL maintainer="Joshua Clifford Reyes <reyesjoshuaclifford@gmail.com>"
LABEL version="1.0.0"
LABEL description="Optimized Dockerfile for php7.1-apache-nginx-laravel."

ADD site-nginx-laravel.conf /etc/nginx/sites-available/

ENTRYPOINT ["/bin/bash"]