FROM php5.6-apache:ubuntu16.04
LABEL maintainer="Joshua Clifford Reyes <reyesjoshuaclifford@gmail.com>"
ADD apache-config-symfony.conf /etc/apache2/sites-enabled/000-default.conf
ENTRYPOINT ["/bin/bash"]
