FROM php5.6-nginx:stable

LABEL maintainer="Joshua Clifford Reyes <reyesjoshuaclifford@gmail.com>"
LABEL version="1.0.0"
LABEL description="Optimized Dockerfile for php5.6-apache-nginx-laravel."

ADD site-nginx-laravel.conf /etc/nginx/sites-available/

ENTRYPOINT ["/bin/bash"]