FROM nodejs8:stable

LABEL maintainer="Joshua Clifford Reyes <reyesjoshuaclifford@gmail.com>"
LABEL version="1.0.0"
LABEL description="Optimized Dockerfile for ionic-dev."

RUN npm install -g ionic cordova

ENTRYPOINT ["/bin/bash"]